apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-sftp-sidecar
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-sftp-sidecar
    spec:
  
      volumes:
      - name: shared-data
        emptyDir: {}

      containers:

      - name: nginx-container
        image: nginx
        volumeMounts:
        - name: shared-data
          mountPath: /usr/share/nginx/html

      - name: sftp-client
        image: jnbs01/docker-sftp-client:latest
        volumeMounts:
        - name: shared-data
          mountPath: /tmp/share
        env:
        - name: SFTPSERVER
          value: "sftp-server.example.com"
        - name: USER
          valueFrom:
            secretKeyRef:
              name: sftp-secret
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: sftp-secret
              key: password
        - name: REMOTEFILE
          value: "/var/sftp/index.html"
        command: ["/bin/sh"]
        args: ["-c", "while true; do sshpass -p $PASSWORD sftp -oStrictHostKeyChecking=no $USER@$SFTPSERVER:$REMOTEFILE;sleep 60;done"]

